name: C++ / Spack / CTest

on:
  push:
    branches: [ main, master, develop, "**/kf/**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]

    env:
      CMAKE_BUILD_TYPE: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set compiler
        run: |
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            sudo apt-get update
            sudo apt-get install -y clang
            echo "CC=clang"  >> $GITHUB_ENV
            echo "CXX=clang++" >> $GITHUB_ENV
          else
            echo "CC=gcc"    >> $GITHUB_ENV
            echo "CXX=g++"   >> $GITHUB_ENV
          fi

      - name: Setup Spack
        uses: spack/setup-spack@v2

      - name: Show Spack version
        run: spack --version

      - name: Concretize & install env (from spack.yaml)
        run: |
          spack env activate -d .
          spack concretize -f
          spack install -j $(nproc)

      - name: List installed packages
        run: |
          spack env activate -d .
          spack find -dlv

      - name: Configure (CMake)
        run: |
          spack env activate -d .
          cmake -S . -B build -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}

      - name: Build
        run: cmake --build build -j $(nproc)

      - name: Test (CTest)
        run: ctest --test-dir build --output-on-failure
